Add test ad unit ids
kmcgill88/admob_flutter pull request #227
Opened 2020-10-05 20:39 UTC by DoctorJohn

Every time I initially figure out ad placements, I have to look up various test ad unit ids. This PR adds them as static members to the different ad classes for easy access. I took the test ad unit ids from the [Android](https://developers.google.com/admob/android/test-ads) and [iOS](https://developers.google.com/admob/ios/test-ads) docs for "Enabling test ads".

IMHO its a useful addition that eases the setup experience.

2020-10-05 21:15 UTC, davidmartos96 commented
Nice PR!
I would include the Platform.isIOS explicitly though. More platforms are coming 😉

2020-10-27 07:11 UTC, EliasDeuss requested changes
I think for future proofing this it should more specific than an if else. As more platforms will be supported by admob.

2020-10-27 10:51 UTC, DoctorJohn commented
@EliasDeuss I extended the platform checks and let the getters throw and `UnsupportedError` in case a platform other than Android or IOS is used.

2020-10-27 22:23 UTC, EliasDeuss approved these changes

2020-10-27 22:39 UTC, merged

2021-03-21 11:04 UTC, jagomf commented
Has this been removed as of `2.0.0-nullsafety.0`? @kmcgill88 @EliasDeuss

2021-03-22 00:03 UTC, kmcgill88 commented
No it should still be there!

2021-03-22 17:43 UTC, jagomf commented
> No it should still be there!

Seems to be gone from latest `2.0.0-nullsafety.0` release.

![image](https://user-images.githubusercontent.com/4032522/112034089-67c30780-8b3e-11eb-81fc-a1aa24d3f081.png)
![image](https://user-images.githubusercontent.com/4032522/112033990-48c47580-8b3e-11eb-8e3d-329eebbef6dc.png)